# 服务配置
Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60

# 应用配置
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: blog_service/storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: blog_service/storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5 # M
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png

# 数据库配置
Database:
  DBType: mysql
  Username: root
  Password: testpwd1202
  Host: 127.0.0.1:3306
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

# JWT验证
JWT:
  # 秘钥
  Secret: chentaoxxx
  # 签发者
  Issuer: blog_service
  # 过期时间
  Expire: 7200


Email:
  Host: smtp.yeah.net
  Port: 465
  UserName: xxx@yeah.net
  Password: xxxxxx
  IsSSL: true
  From: xxx@yeah.net
  To:
    - xxx@yeah.net

Limiter:

  Limits:
    - Key: "/auth"
      FillInterval: 1
      Capacity: 10
      Quantum: 10

    - Key: "/api/v1/tags"
      FillInterval: 1
      Capacity: 10
      Quantum: 10
